sudo: required
cache:
  - apt

language: generic
matrix:
  include:
  - name: "Trusty kinetic"
    dist: trusty
  - name: "Bionic melodic"
    dist: bionic
env:
  global:
    - ROS_CI_DESKTOP="`lsb_release -cs`"  # e.g. [precise|trusty|...]
    - CI_SOURCE_PATH=$(pwd)
    - CATKIN_OPTIONS=$CI_SOURCE_PATH/catkin.options
    - ROS_PARALLEL_JOBS='-j8 -l6'
    # Set the python path manually to include /usr/-/python2.7/dist-packages
    # as this is where apt-get installs python packages.
    - PYTHONPATH=$PYTHONPATH:/usr/lib/python2.7/dist-packages:/usr/local/lib/python2.7/dist-packages

################################################################################

before_install:

   #install gtest
  - sudo apt-get update                     >/dev/null # suppress output
  - sudo apt-get install cmake              >/dev/null # suppress output
  - sudo apt install libgtest-dev           >/dev/null # suppress output
  - cd /usr/src/gtest/                      >/dev/null # suppress output
  - sudo mkdir build && cd build            >/dev/null # suppress output
  - sudo cmake .. -DBUILD_SHARED_LIBS=ON    >/dev/null # suppress output
  - sudo make                               >/dev/null # suppress output
  - sudo cp *.so /usr/lib                   >/dev/null # suppress output
  - cd ~/                                   >/dev/null # suppress output


# Create a catkin workspace with the package under integration.
install:
  - mkdir -p ~/catkin_ws/src
  - cd ~/catkin_ws
  # Add the package under integration to the workspace using a symlink.
  - cd ~/catkin_ws/src
  - ln -s $CI_SOURCE_PATH .

  #install deb-packaged dependencies
  - cd ~/catkin_ws/src/control-toolbox/ct
  - chmod 775 install_deps.sh
  - sudo ./install_deps.sh

  #install kindr
  - cd ~/catkin_ws/src/
  - git clone https://github.com/ANYbotics/kindr.git
  - cd kindr
  - mkdir -p build && cd build
  - cmake .. && make
  - sudo make install
  
script:
  - cd ~/catkin_ws/src/control-toolbox/ct
  - sudo ./build_ct.sh -DUSE_CLANG=true -DBUILD_TESTS=true -DCMAKE_BUILD_TYPE=Release -DCMAKE_CXX_FLAGS="-w"
